# Generated by Django 4.1.9 on 2023-06-03 09:41

import DigitalMarketing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cVideoId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoID', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='videoID', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y/%m', validators=[DigitalMarketing.validators.file_size])),
            ],
        ),
    ]
