# Generated by Django 4.2.1 on 2023-05-14 10:07

import DigitalMarketing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DigitalMarketing', '0002_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y', validators=[DigitalMarketing.validators.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='video_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
            ],
        ),
    ]
