# Generated by Django 4.1.9 on 2023-06-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0005_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaignquestionresponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(db_column='Response', max_length=2000)),
            ],
            options={
                'db_table': 'CampaignQuestionResponse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaignvideo',
            fields=[
                ('campaignvideoid', models.CharField(db_column='CampaignVideoID', max_length=255, primary_key=True, serialize=False)),
                ('campaignid', models.CharField(blank=True, db_column='CampaignID', max_length=255, null=True)),
                ('previousvideoid', models.CharField(blank=True, db_column='PreviousVideoID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CampaignVideo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoid', models.CharField(db_column='VideoID', max_length=250)),
                ('videotitle', models.CharField(blank=True, db_column='VideoTitle', max_length=255, null=True)),
                ('videopath', models.CharField(blank=True, db_column='VideoPath', max_length=255, null=True)),
                ('approveddate', models.DateTimeField(blank=True, db_column='ApprovedDate', null=True)),
            ],
            options={
                'db_table': 'tb_Approve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCampaignquestion',
            fields=[
                ('campaignquestionid', models.CharField(db_column='CampaignQuestionID', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_CampaignQuestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbQuestion',
            fields=[
                ('questionid', models.CharField(db_column='QuestionID', max_length=255, primary_key=True, serialize=False)),
                ('questiontext', models.CharField(db_column='QuestionText', max_length=2000)),
                ('questionresponse', models.CharField(db_column='QuestionResponse', max_length=4000)),
            ],
            options={
                'db_table': 'tb_Question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoid', models.CharField(db_column='VideoID', max_length=250)),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=255, null=True)),
                ('videoname', models.CharField(blank=True, db_column='videoName', max_length=255, null=True)),
                ('approver', models.CharField(blank=True, db_column='Approver', max_length=255, null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
            ],
            options={
                'db_table': 'tb_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('userid', models.CharField(db_column='UserID', max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=250)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUserrole',
            fields=[
                ('userroleid', models.CharField(db_column='UserRoleID', max_length=255, primary_key=True, serialize=False)),
                ('userrolename', models.CharField(db_column='UserRoleName', max_length=250)),
            ],
            options={
                'db_table': 'tb_UserRole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbVideo',
            fields=[
                ('videoid', models.CharField(db_column='VideoID', max_length=255, primary_key=True, serialize=False)),
                ('previousvideoid', models.CharField(blank=True, db_column='PreviousVideoID', max_length=255, null=True)),
                ('videoname', models.CharField(db_column='VideoName', max_length=2000)),
                ('videopath', models.CharField(db_column='VideoPath', max_length=2000)),
                ('videotranscription', models.TextField(db_column='VideoTranscription')),
            ],
            options={
                'db_table': 'tb_Video',
                'managed': False,
            },
        ),
    ]
