# Generated by Django 4.2.1 on 2023-05-15 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='video_details',
        ),
    ]
