# Generated by Django 4.2.1 on 2023-05-15 02:07

import DigitalMarketing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DigitalMarketing', '0006_delete_video_delete_video_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%m/%y', validators=[DigitalMarketing.validators.file_size])),
            ],
        ),
        migrations.CreateModel(
            name='video_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%m/%y', validators=[DigitalMarketing.validators.file_size])),
                ('quality', models.BooleanField()),
                ('qualitycommmand', models.CharField(max_length=100)),
                ('complaint', models.BooleanField()),
                ('complaintcommand', models.CharField(max_length=100)),
                ('transcribe', models.CharField(max_length=1000)),
            ],
        ),
    ]
