# Generated by Django 4.1.9 on 2023-06-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0006_campaignquestionresponse_campaignvideo_tbapprove_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
