# Generated by Django 4.1.9 on 2023-07-09 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DigitalMarketing', '0007_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbapproverQuestion',
            fields=[
                ('questionid', models.CharField(db_column='QuestionID', max_length=255, primary_key=True, serialize=False)),
                ('questiontext', models.CharField(db_column='QuestionText', max_length=2000)),
            ],
            options={
                'db_table': 'tb_ApproverQuestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='video_Details',
            fields=[
                ('VideoPath', models.CharField(db_column='videopath', max_length=2000, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'videodetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, db_column='UserID', max_length=255)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=255)),
                ('userroleid', models.CharField(blank=True, db_column='UserRoleId', max_length=255)),
                ('vendor', models.CharField(blank=True, db_column='Vendor', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
