# Generated by Django 4.1.9 on 2023-05-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='video_details',
        ),
    ]
