# Generated by Django 4.1.9 on 2023-05-16 06:36

import DigitalMarketing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DigitalMarketing', '0008_delete_video_delete_video_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbVideo',
            fields=[
                ('videoid', models.IntegerField(db_column='VideoID', primary_key=True, serialize=False)),
                ('previousvideoid', models.IntegerField(db_column='PreviousVideoID')),
                ('videoname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VideoName', max_length=2000)),
                ('videopath', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VideoPath', max_length=2000)),
                ('videotranscription', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VideoTranscription')),
            ],
            options={
                'db_table': 'tb_Video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%m/%y', validators=[DigitalMarketing.validators.file_size])),
            ],
        ),
    ]
