# Generated by Django 4.1.9 on 2023-05-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaignvideo',
            fields=[
                ('campaignvideoid', models.IntegerField(db_column='CampaignVideoID', primary_key=True, serialize=False)),
                ('campaignid', models.IntegerField(db_column='CampaignID')),
                ('previousvideoid', models.IntegerField(db_column='PreviousVideoID')),
            ],
            options={
                'db_table': 'CampaignVideo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCampaignquestion',
            fields=[
                ('campaignquestionid', models.IntegerField(db_column='CampaignQuestionID', primary_key=True, serialize=False)),
                ('userroleid', models.IntegerField(db_column='UserRoleID')),
                ('questionid', models.IntegerField(db_column='QuestionID')),
            ],
            options={
                'db_table': 'tb_CampaignQuestion',
                'managed': False,
            },
        ),
    ]
