# Generated by Django 4.1.9 on 2023-05-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0011_tbquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Campaignvideo',
        ),
        migrations.DeleteModel(
            name='TbCampaignquestion',
        ),
        migrations.DeleteModel(
            name='TbQuestion',
        ),
        migrations.DeleteModel(
            name='TbVideo',
        ),
    ]
