# Generated by Django 4.1.9 on 2023-05-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0014_campaignquestionresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('userid', models.IntegerField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserName', max_length=250)),
            ],
            options={
                'db_table': 'tb_User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUserrole',
            fields=[
                ('userroleid', models.IntegerField(db_column='UserRoleID', primary_key=True, serialize=False)),
                ('userrolename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserRoleName', max_length=250)),
            ],
            options={
                'db_table': 'tb_UserRole',
                'managed': False,
            },
        ),
    ]
