# Generated by Django 4.1.9 on 2023-05-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0015_tbuser_tbuserrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='cVideoId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoID', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UserRoleName', max_length=250)),
            ],
        ),
    ]
