# Generated by Django 4.1.9 on 2023-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0016_cvideoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvideoid',
            name='VideoID',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='videoID', max_length=250),
        ),
    ]
