# Generated by Django 4.1.9 on 2023-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0019_rename_status_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='reason',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Reason', default=1, max_length=250),
            preserve_default=False,
        ),
    ]
