# Generated by Django 4.1.9 on 2023-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0021_alter_status_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='reason',
            field=models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Reason', max_length=250, null=True),
        ),
    ]
