# Generated by Django 4.1.9 on 2023-05-28 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0022_alter_status_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
