# Generated by Django 4.1.9 on 2023-05-28 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0023_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoID', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='videoID', max_length=250)),
                ('approvedDate', models.DateField(default=datetime.datetime.now)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='DigitalMarketing.tbuser')),
            ],
        ),
    ]
