# Generated by Django 4.1.9 on 2023-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0024_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve',
            name='VideoPath',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='videoPath', default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approve',
            name='VideoTitle',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='videoTitle', default=1, max_length=250),
            preserve_default=False,
        ),
    ]
