# Generated by Django 4.1.9 on 2023-05-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0025_approve_videopath_approve_videotitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='VideoName',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='videoName', default=1, max_length=250),
            preserve_default=False,
        ),
    ]
