# Generated by Django 4.1.9 on 2023-05-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0027_approve_approvername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approve',
            name='ApproverName',
        ),
        migrations.AddField(
            model_name='status',
            name='ApproverName',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Approver', default=1, max_length=250),
            preserve_default=False,
        ),
    ]
