# Generated by Django 4.1.9 on 2023-05-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0028_remove_approve_approvername_status_approvername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='approvedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
