# Generated by Django 4.1.9 on 2023-05-30 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0029_alter_approve_approveddate_alter_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='approvedDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
