# Generated by Django 4.1.9 on 2023-05-30 17:44

import DigitalMarketing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0030_alter_approve_approveddate_alter_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video%D/%m/%y', validators=[DigitalMarketing.validators.file_size]),
        ),
    ]
