# Generated by Django 4.1.9 on 2023-05-30 17:48

import DigitalMarketing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalMarketing', '0031_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/%y/%m', validators=[DigitalMarketing.validators.file_size]),
        ),
    ]
